blog/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from wzxblog import views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wzxblog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', views.archives.as_view(), name='index')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wzxblog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'
urlpatterns = [
    # 用户注册的路由url
    path("registe/", views.registe, name='registe'),

    path("login/", views.login, name='login'),

    path("logout/", views.logout, name='logout'),

    path("", views.indexview.as_view(), name='index'),

    re_path("archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$", views.archives.as_view(), name='archives'),

    re_path('category/(?P<categoryid>[0-9]+)/$', views.categoryview, name='category'),

    re_path("tag/(?P<tagid>[0-9]+)/$", views.tagview.as_view(), name='tag'),

    path("author/<int:userid>/", views.authorview.as_view(), name='author'),

    path("blog_detail/<int:blogid>/", views.blogdatailview.as_view(), name='blog_detail'),
]

wzxblog/forms.py
from django import forms
from . import models
from django.core.exceptions import ValidationError


class reg_form(forms.Form):
    username = forms.CharField(
        max_length=20,
        label="账号",
        error_messages={
            "max_length": "账号最长20位",
            "required": "账号必输",
            "min_length": "账号最短6位"
        },
        # <input type='text'/>
        widget=forms.widgets.TextInput(
            attrs={'class': "form-control"},
        )
    )

    password = forms.CharField(
        max_length=6,
        label="密码",
        error_messages={
            "min_length": "密码最短6位",
            "required": "密码不能为空",
            "max_length": "密码最长20位"
        },
        # <input type='password'/>
        widget=forms.widgets.PasswordInput(
            attrs={'class': "form-control"},
        )
    )

    repassword = forms.CharField(
        max_length=6,
        label="确认密码",
        error_messages={
            "min_length": "密码最短6位",
            "required": "密码不能为空"
        },
        # <input type='password'/>
        widget=forms.widgets.PasswordInput(
            attrs={'class': "form-control"},
        )
    )

    nikename = forms.CharField(
        max_length=20,
        label="昵称",
        error_messages={
            "max_length": "昵称最大20字",
        },
        initial="王振兴",
        widget=forms.widgets.TextInput(
            attrs={'class': "form-control"},
        )
    )

    email = forms.EmailField(
        label="邮箱",
        error_messages={
            "invalid": "请输入正确的邮箱",
            "required": "邮箱不能为空",
        },
        widget=forms.widgets.EmailInput(
            attrs={'class': "form-control"},
        )
    )

    telephone = forms.CharField(
        label="电话",
        required=False,
        error_messages={
            'max_length': "手机号11位"
        },
        widget=forms.widgets.TextInput(
            attrs={'class': "form-control"},
        )
    )

    head_img = forms.ImageField(
        label="头像",
        widget = forms.widgets.FileInput(
            attrs={'style': "display:none"},
        )
    )

    # 确认密码和密码一致性检查
    def clean_repassword(self):
        passwd = self.cleaned_data.get('password')
        repasswd = self.cleaned_data.get('repassword')
        if repasswd and repasswd != passwd:
            self.add_error("repassword", ValidationError("两次输入密码不一致"))
        else:
            return repasswd

    # username存在性
    def clean_username(self):
        input_user = self.cleaned_data.get('username')

        # ORM
        user = models.Reguser.objects.filter(username=input_user)
        if user:
            self.add_error("username", ValidationError("用户账号已注册."))
        else:
            return input_user

    # def clean(self):
    #     self.cleaned_data

    # django 表单检查的顺序 is_valid() clean_xxx clean
    # 1.检查基础规则
    # 2.clean_xxx
    # 3.clean

templates/blog/archives.html
{% extends 'base.html' %}
{% block main %}
    <ol class="breadcrumb">
      <li><a href="#">日期</a></li>
      <li class="active">{{ year }}年{{ month }}月</li>
    </ol>
    {% include 'blog_list.html' %}
{% endblock main %}

templates/blog/author.html
{% extends 'base.html' %}
{% block main %}
    <ol class="breadcrumb">
      <li><a href="#">作者</a></li>
      <li class="active">{{ author.nikename }}</li>
    </ol>
    {% include 'blog_list.html' %}
{% endblock main %}

templates/blog/blog_detail.html
{% extends 'base.html' %}
{% block main %}
    <article class="blog">
    <header class="entry-header">
        <h2>{{ blog.title }}</h2>
        <div class="entry-meta-detail">
            <span class="blog-category">
                <a href="{% url 'blog:category' blog.category.id %}">{{ blog.category.name }}</a>
            </span>
            <span class="blog-date">
                <a href="#">{{ blog.create_time }}</a>
            </span>
            <span class="blog-author">
                <a href="{% url 'blog:author' blog.author.id %}">{{ blog.author.nikename }}</a>
            </span>
            <span class="views-count">
                <a href="#">{{ blog.views }}阅读</a>
            </span>
        </div>
        </header>
     <div class="entry-content clearfix">
            {{ blog.body|safe }}
     </div>
    </article>
    {% include 'blog_list.html' %}
{% endblock main %}

templates/blog/category.html
{% extends 'base.html' %}
{% block main %}
    <ol class="breadcrumb">
      <li><a href="#">分类</a></li>
      <li class="active">{{ Category.name }}</li>
    </ol>
    {% include 'blog_list.html' %}
{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
<div class="jumbotron">
    <h1>你好，我是王振兴</h1>
    <p>欢迎你来到我的博客主页</p>
    {% if request.user.username %}
        <p><a class="btn btn-primary btn-lg" href="#" role="button">写博文</a></p>
    {% else %}
        <p><a class="btn btn-primary btn-lg" href="/registe/" role="button">新用户注册</a></p>
    {% endif %}
</div>
    {% include 'blog_list.html' %}
{% endblock main %}

templates/blog/login.html
{% load static %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>wzxBlog | 小王博客</title>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
</head>

<body style="padding-top:70px;">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="javascript:;">wzxBlog</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">首页</a></li>
            <li><a href="#">关于</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="page-header">
                <h2 style="text-align:center;">用户登陆
                    <small>&nbsp;海内存知己，天涯若比邻!</small>
                </h2>
            </div>
            <form method="POST" action="{% url 'blog:login' %}" class="form-horizontal col-md-6 col-md-offset-3 login-form" >
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">用户名</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="username" name="username" placeholder="用户名">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">密码</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="password" name="password" placeholder="密码">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button id="loginbutton" class="btn btn-primary" type="button" style="padding:8px 15px;">登录</button>
                        <a class="btn btn-link" href="/registe/" style="padding:8px 15px;">新用户注册</a>
                        <span id="errormsg" style="color:red">{{ error }}</span>
                    </div>
                </div>
            </form>
        </div>
    </div> <!-- /container -->
    <nav class="navbar navbar-default navbar-fixed-bottom">
      <div style="margin-top:15px;text-align:center;"> wzxBlog&nbsp;小王博客&nbsp;&copy;.WZX</div>
    </nav>
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script>
        $("#loginbutton").click(function(){
            $.ajax({
                url: '/login_ajax/',
                type: 'POST',
                data: {
                    // 用户名
                    username: $("#username").val(),
                    // 密码
                    password: $("#password").val(),
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                // 请求成功回调函数
                success: function(data){
                    // 打印返回数据
                    console.log(data);
                    if(data.code === 0){
                        window.location.href = 'index.html/';
                    }else{
                        // 否则显示错误信息
                        $("#errormsg").text(data.message);
                    }
                }
            });
        });
    </script>
</body>
</html>

templates/blog/registe.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>wzxBlog | 小王博客</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body style="padding-top:70px;">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="javascript:;">wzxBlog | 小王博客</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">首页</a></li>
            <li><a href="#">关于</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="page-header">
                    <h2>新用户注册
                        <small>&nbsp;欢迎您，来到我的博客!</small>
                    </h2>
                </div>
                <form novalidate action="/registe/" method="POST" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ formobj.username.id_for_label }}" class="col-sm-2 control-label">
                            {{ formobj.username.label }}
                        </label>
                        <div class="col-sm-8">
                            {{ formobj.username }}
                            <span class="help-block">{{ formobj.username.errors.0 }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ formobj.password.id_for_label }}" class="col-sm-2 control-label">
                            {{ formobj.password.label }}
                        </label>
                        <div class="col-sm-8">
                            {{ formobj.password }}
                            <span class="help-block">{{ formobj.password.errors.0 }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ formobj.repassword.id_for_label }}" class="col-sm-2 control-label">
                            {{ formobj.repassword.label }}
                        </label>
                        <div class="col-sm-8">
                            {{ formobj.repassword }}
                            <span class="help-block">{{ formobj.repassword.errors.0 }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ formobj.nikename.id_for_label }}" class="col-sm-2 control-label">
                            {{ formobj.nikename.label }}
                        </label>
                        <div class="col-sm-8">
                            {{ formobj.nikename }}
                            <span class="help-block">{{ formobj.nikename.errors.0 }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ formobj.email.id_for_label }}" class="col-sm-2 control-label">
                            {{ formobj.email.label }}
                        </label>
                        <div class="col-sm-8">
                            {{ formobj.email }}
                            <span class="help-block">{{ formobj.email.errors.0 }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ formobj.telephone.id_for_label }}" class="col-sm-2 control-label">
                            {{ formobj.telephone.label }}
                        </label>
                        <div class="col-sm-8">
                            {{ formobj.telephone }}
                            <span class="help-block">{{ formobj.telephone.errors.0 }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{ formobj.head_img.label }}</label>
                        <div class="col-sm-8">
                            <label for="{{ formobj.head_img.id_for_label }}" class="col-sm-2 control-label">
                                <img id="head-img" class='img-circle' src="/static/image/headimg.jpg" style="height:100px;width:100px;">
                            </label>
                            {{ formobj.head_img }}
                            <span class="help-block"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input type="submit" class="btn btn-primary" style="padding:8px 15px;" value="注册"></input>
                            <a href="/login/" class="btn btn-link" style="padding:8px 15px;">已有用户，登录</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-default navbar-fixed-bottom">
      <div style="margin-top:15px;text-align:center;"> wzxBlog&nbsp;小王博客&nbsp;.WZX</div>
    </nav>
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
        // 找到头像的input标签绑定change事件
        $("#id_head_img").change(function () {
            var filerd = new FileReader(); //  创建一个读取文件的对象
            filerd.readAsDataURL(this.files[0]); // 读取你选中的那个文件
            filerd.onload = function () {
                $("#head-img").attr("src",  filerd.result);// 2. 把图片加载到img标签中
            };
        });
    </script>
</body>
</html>

templates/blog/tag.html
{% extends 'base.html' %}
{% block main %}
    <ol class="breadcrumb">
      <li><a href="#">标签</a></li>
      <li class="active">{{ tags.name }}</li>
    </ol>
    {% include 'blog_list.html' %}
{% endblock main %}