blog/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from wzxblog import views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wzxblog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', views.archives.as_view(), name='index')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wzxblog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'
urlpatterns = [
    # 用户注册的路由url
    path("registe/", views.registe, name='registe'),

    path("login/", views.login, name='login'),

    path("logout/", views.logout, name='logout'),

    path("", views.indexview.as_view(), name='index'),

    re_path("archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$", views.archives.as_view(), name='archives'),

    re_path('category/(?P<categoryid>[0-9]+)/$', views.categoryview, name='category'),

    re_path("tag/(?P<tagid>[0-9]+)/$", views.tagview.as_view(), name='tag'),

    path("author/<int:userid>/", views.authorview.as_view(), name='author'),

    path("blog_detail/<int:blogid>/", views.blogdatailview.as_view(), name='blog_detail'),
]

templates/base.html
{% load static %}
{% load blog_tag %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>wzxBlog | 小王博客</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link href="{% static 'css/style.css' %}"rel="stylesheet">
</head>
<body style="padding-top:70px;">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">wzxblog | 小王博客</a>
            </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">首页 <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">精华文章</a></li>
                    {% if request.user.username %}
                        <li><a href="author/{{ request.user.id }}">我的</a></li>
                    {% endif %}
{#                    <li class="dropdown">#}
{#                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>#}
{#                        <ul class="dropdown-menu">#}
{#                            <li><a href="#">Action</a></li>#}
{#                            <li><a href="#">Another action</a></li>#}
{#                            <li><a href="#">Something else here</a></li>#}
{##}
{#                            <li role="separator" class="divider"></li>#}
{#                            <li><a href="#">Separated link</a></li>#}
{#                            <li role="separator" class="divider"></li>#}
{#                            <li><a href="#">One more separated link</a></li>#}
{#                        </ul>#}
{#                    </li>#}
                </ul>
{#                <form class="navbar-form navbar-left">#}
{#                    <div class="form-group">#}
{#                        <input type="text" class="form-control" placeholder="Search">#}
{#                    </div>#}
{#                    <button type="submit" class="btn btn-default">Submit</button>#}
{#                </form>#}
                <ul class="nav navbar-nav navbar-right">

                    {% if request.user.username %}
                        <li><a href="#">{{ request.user.username }}</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">个人中心 <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="author/{{ request.user.id }}">我的博文</a></li>
                                <li><a href="#">我的收藏</a></li>
                                <li><a href="#">个人信息</a></li>
                                <li><a href="#">修改密码</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="/logout/">退出</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'blog:login' %}">登录</a></li>
                        <li><a href="{% url 'blog:registe' %}">注册</a></li>
                    {% endif %}
                </ul>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="content-boby" style="margin-bottom:80px">
        <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>

            <aside class="col-md-4">
                {% if author %}
                <div class="panel panel-default">
                    <div class="panel-heading">作者信息</div>
                    <div class="panel-body" style="text-align: center;">
                        <img src="/media/{{ blog.author.head_img }}" alt="{{ author.nikename }}"
                             style="width: 100px; height: 100px;" class="img-circle">
                        <h4>{{ author.nikename }}</h4>
                    </div>
                </div>
                {% endif %}
                <div class="panel panel-default">
                    <div class="panel-heading">最新文章</div>
                    <div class="panel-body">
                        {% get_new_blogs as new_blog_list %}
                        <ul>
                            {% for blog in new_blog_list %}
                             <li><a href="{% url 'blog:blog_detail' blog.id %}">{{ blog.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                 <div class="panel panel-default">
                    <div class="panel-heading">分类</div>
                    <div class="panel-body">
                    {% get_categories as categories_list %}
                        <ul>
                            {% for Category in categories_list %}
                             <li><a href="{% url 'blog:category' Category.id %}">
                                 {{ Category.name }}
                             <span class="post-count">({{ Category.num_blogs }})</span>
                             </a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                 <div class="panel panel-default">
                    <div class="panel-heading">标签</div>
                    <div class="panel-body">
                        <div class="tag-list">
                        {% get_tags as tags_list %}
                            <ul>
                            {% for Tag in tags_list %}
                             <li><a href="{% url 'blog:tag' Tag.id %}">
                                 {{Tag.name }}
                                 <span class="post-count">({{ Tag.num_blogs }})</span>
                             </a></li>
                            {% endfor %}
                        </ul>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">日期</div>
                    <div class="panel-body">
                         {% get_arhcives as data_list %}
                            <ul>
                            {% for data in data_list %}
                             <li><a href="{% url 'blog:archives' data.year data.month %}">
                                 {{data.year }}年{{ data.month }}月
                             </a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </aside>
        </div>
        </div>
    </div>

    <nav class="navbar navbar-default navbar-fixed-bottom">
      <div style="margin-top:15px;text-align:center;"> wzxBlog&nbsp;小王博客&nbsp;.WZX</div>
    </nav>
</body>
</html>

templates/blog_list.html
            {% for blog in blog_list %}
                <div class="media">
                {% if not author %}
                  <div class="media-left">
                      <a href='author/{{ blog.author.id }}'>
                          <img class="media-object img-circle" src="/media/{{ blog.author.head_img }}" alt="进入作者主页"
                          style="width:100px;height:100px;">
                      </a>
                  </div>
                {% endif %}
                    <div class="media-body">
                        <h4 class="media-heading"><a href="{% url 'blog:blog_detail' blog.id %}">{{ blog.title }}</a></h4>
                        <p></p>
                        <div class="entry-content">
                            <span class="blog-category"><a href="#">{{ blog.category.name }}</a> </span>
                            <span class="blog-tags">
                                <a href="#">
                                    <time class="entry-date"datetime="{{ blog.create_time }}" >
                                        {{ blog.create_time }}
                                    </time>
                                </a>
                            </span>
                            <span class="blog-author"><a href="#">{{ blog.author.nikename }}</a> </span>
                            <span class="comments-link"><a href="#">123评论</a> </span>
                            <span class="views-count"><a href="#">{{ blog.views }}阅读</a> </span>
                        </div>
                  </div>
                </div>
                {% endfor %}